### ISSUE TITLE
"Caballo" does not return any result

### ISSUE THREAD

**Issue by Akronix** [javierhonduco/dulcinea#1]
Hello.

I don't know why but when querying for "caballo" the response field is empty http://dulcinea.herokuapp.com/api/?query=caballo, however it should return [this from the DRAE.](http://lema.rae.es/drae/?val=caballo)

Maybe it's because the response is too long?

**Comment by javierhonduco** [comment]
Hi!

First of all, thanks for reporting the bug.
I don't know whether that's a cache problem or something else, because the id for `caballo` seems to work: http://dulcinea.herokuapp.com/api/?query=46BZ4EFsMDXX2xFYaTWK.
I'll take a further look and reach you,

Greetings!

**Comment by javierhonduco** [comment]
Closing as it returns the appropriate response.
