### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by rockneurotiko** [javierhonduco/dulcinea#2]
The heroku app seems to don't return any result.

**Comment by javierhonduco** [comment]
Hi,

First of all sorry for having it down.
The problem has been that the RAE has changed quite a lot of things. I fixed nebrija from [this commit](https://github.com/javierhonduco/nebrija/commit/5747f168cecf8281fae52f4f5deb66ce234254a1) (the library that does the heavy lifting) and the changes and not backwards compatible.
I had no time to make it behave like the previous versions. :person_frowning:  
That's quite unfortunate so if I find time I should change that.

Right now the only solution that I can do is updating `dulcinea` to use the new the library and hence return the data following the new API and breaking previous clients.

What do you think?

**Comment by javierhonduco** [comment]
ping @rockneurotiko

**Comment by javierhonduco** [comment]
Closing as it's already up & running.
