### ISSUE TITLE
frontend and api stopped working

### ISSUE THREAD

**Issue by matallo** [javierhonduco/dulcinea#4]
queries through http://dulcinea.herokuapp.com/ stopped working, always returning the same response "La palabra no existe en la rae" despite the word exists

**steps to reproduce**

for example, taking the word "casa", here's the link in RAE website http://dle.rae.es/?id=7lsKMtR

when sending the query though the search box in dulcinea, an alert appears

<img width="577" alt="screen shot 2017-03-04 at 20 49 48" src="https://cloud.githubusercontent.com/assets/36676/23581796/2d0cfa20-011c-11e7-9540-33901b5ce4a7.png">

inspecting the HTTP request to http://dulcinea.herokuapp.com/api/word/casa in developer tools, the response is `404`

```
➜  ~ curl http://dulcinea.herokuapp.com/api/word/casa
{
  "status": "error",
  "message": "Word/id does not exist. Sorry."
}%
```

the same occurs when sending a HTTP request through http://dulcinea.herokuapp.com/api/?query=casa as in the `README.md`

```
➜  ~ curl -I http://dulcinea.herokuapp.com/api/\?query\=casa
HTTP/1.1 404 Not Found
Server: Cowboy
Connection: keep-alive
Date: Sat, 04 Mar 2017 19:45:16 GMT
Content-Type: text/html;charset=utf-8
X-Cascade: pass
Content-Length: 18
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Via: 1.1 vegur
```

**Comment by javierhonduco** [comment]
Hi,

First of all, thanks for the detailed report.
It seems that RAE changed its "auth" method again *sigh*.

Everything's implemented [here](https://github.com/javierhonduco/dulcinea). This project is not more than the HTTP layer that simply calls the library.

Let me have a look and I will get back to you as soon as I have something.

**Comment by javierhonduco** [comment]
I've applied a patch to `nebrija`. That should make it work again, but one never knows, as the way they generate their "auth" tokens is pretty... interesting...

[This](https://github.com/javierhonduco/nebrija/pull/13/files) is the PR in the underlying library, and [this commit](https://github.com/javierhonduco/dulcinea/commit/8c019ea8ec2c03ff69669779c3af4d2bbe5535ff) in `dulcinea` updates the `Gemfile.lock` to use the new version of `nebrija`.

Cheers,

**Comment by matallo** [comment]
BOOM
